server.modules += ( "mod_proxy" )

$HTTP["url"] =~ "^/(.*)$" {
  proxy.server = ( "" => ( ( "host" => "XXXXWEBSERVERIPHTTPSXXXX", "port" => XXXXPORTXXXX ) ) )
  proxy.header = (
    "map-url" => (
      "^/(.*)$" => "/$1"
    )
  )
}
