include "modules.conf"
include "mimetypes.conf"

server.document-root        = "/var/www/html"

$SERVER["socket"] == ":443" {
ssl.engine = "enable"
ssl.pemfile = "XXXXHOMEXXXX/ssl/live/XXXXWEBSITEURLXXXX/privkey.pem"
ssl.ca-file = "XXXXHOMEXXXX/ssl/live/XXXXWEBSITEURLXXXX/fullchain.pem"
ssl.openssl.ssl-conf-cmd = ("Ciphersuites" => "TLS_AES_128_GCM_SHA256")+("Protocol" => "-ALL, TLSv1.3")+("Curves" => "secp384r1")
ssl.disable-client-renegotiation = "enable"

#$HTTP["url"] =~ "^/(.*)$" {
#  proxy.server = ( "" => ( ( "host" => "10.0.1.4", "port" => 443 ) ) )
#  proxy.header = (
#    "map-url" => (
#      "^/(.*)$" => "/$1"
#    )
#  )
#}
}
