#!/bin/sh
###########################################################################################################
# Description: We need an SSL certificate for each of our webservers and we generate our cerificate here.
# We want an authoritative webserver to generate the certificate so we put in a sleep so that the first
# webserver to claim to be authoritative becomes authoritative by writing a lock file to the datastore.
# A certificate won't be generated by a webserver unless it has the lock. Certificates are only generated
# by the first webserver that finds that its current certificate has expired. This certificate is generated and then
# distributed written to the datastore and then distributed to the other webservers as a "fresh" certificate which
# will have a full lifespan again. 
# Date: 16/11/2016
# Author: Peter Winter
###########################################################################################################
# License Agreement:
# This file is part of The Agile Deployment Toolkit.
# The Agile Deployment Toolkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# The Agile Deployment Toolkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with The Agile Deployment Toolkit.  If not, see <http://www.gnu.org/licenses/>.
#######################################################################################################
#######################################################################################################
#set -x

if ( [ "`${HOME}/providerscripts/datastore/configwrapper/AgeOfConfigFile.sh ssl/SSL_UPDATING`" -gt "300" ] )
then
	${HOME}/providerscripts/datastore/configwrapper/DeletetFromConfigDatastore.sh ssl/SSL_UPDATING
fi

/bin/sleep "`/usr/bin/shuf -i1-300 -n1`"

if ( [ "`${HOME}/providerscripts/datastore/configwrapper/ListFromConfigDatastore.sh ssl/SSL_UPDATING`" != "" ] )
then
	exit
else
	${HOME}/providerscripts/datastore/configwrapper/PutToConfigDatastore.sh ssl/SSL_UPDATING
fi

${HOME}/security/ValidateSSLCertificate.sh

/bin/sleep 300

${HOME}/providerscripts/datastore/configwrapper/DeletetFromConfigDatastore.sh ssl/SSL_UPDATING




